apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-authority
  - cert-manager
  - envoy-gateway
  - external-secret
  - gateway
  - longhorn
  - metallb
  - postgresql
  - valkey
