apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-postgresql
  namespace: gitlab-production
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  storage:
    size: 20Gi
    storageClass: longhorn

  bootstrap:
    initdb:
      database: gitlab
      owner: gitlab
      secret:
        name: gitlab-postgresql-app
