apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: homeserver

  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.16.0
    helm:
      releaseName: metallb
      values: |
        prometheus:
          serviceMonitor:
            enabled: false
          podMonitor:
            enabled: false
          prometheusRule:
            enabled: false

        frrk8s:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
