apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-configuration
  namespace: argocd
spec:
  project: homeserver

  source:
    repoURL: https://github.com/development-martin-rein/homeserver.git
    targetRevision: main
    path: cluster/infrastructure/metallb/configuration

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
