apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-valkey-data
  namespace: gitlab-production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
