apiVersion: v1
kind: Service
metadata:
  name: gitlab-valkey
  namespace: gitlab-production
spec:
  selector:
    app: gitlab-valkey
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
