apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - management/argocd
  - infrastructure/cert-manager
  - infrastructure/longhorn
  - infrastructure/postgresql
  - infrastructure/valkey
  - infrastructure/external-secret
  - management/infisical
