apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchdb
  namespace: argocd
spec:
  project: homeserver
  source:
    repoURL: https://github.com/MartinRein/homeserver.git
    targetRevision: main
    path: application/couchdb
  destination:
    server: https://kubernetes.default.svc
    namespace: couchdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
