apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:latest
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: mariadb-nextcloud
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb
                  key: password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "nextcloud.home.lan"
            - name: TRUSTED_PROXIES
              value: "10.42.0.0/16 10.43.0.0/16 192.168.178.240"
            - name: OVERWRITEHOST
              value: "nextcloud.home.lan"
            - name: OVERWRITEPROTOCOL
              value: "https"
            - name: OVERWRITECLIURL
              value: "https://nextcloud.home.lan"
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
