apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-production
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 2m
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/production
  dependsOn:
    - name: cluster-infra
  timeout: 10m
