apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 10m
  retryInterval: 2m
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system          # so heißt dein GitRepository in flux-system
  path: ./kustomize/infra      # zeigt auf den Infra-Ordner im Repo
  timeout: 5m
