apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - secrets.yaml

  - infra-cert-manager.yaml
  - infra-cloudnative-pg.yaml
  - infra-longhorn.yaml
  - infra-metallb.yaml
  - infra-metallb-config.yaml
  - infra-envoy-gateway.yaml
  - infra-gateway.yaml

  - production-apps-gitlab-postgresql.yaml
  - production-apps-gitlab-valkey.yaml
  - production-apps-gitlab-object-storage.yaml
  - production-apps-gitlab.yaml
  - production-apps-nextcloud-db.yaml
  - production-apps-nextcloud.yaml
  - production-apps-obsidian-livesync.yaml

  - apps-staging.yaml
