apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infra-cert-manager.yaml
  - infra-longhorn.yaml
  - infra-metallb.yaml
  - infra-metallb-config.yaml
  - infra-envoy-gateway.yaml
  - infra-gateway.yaml
  - apps-production.yaml
  - apps-staging.yaml
