apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchdb-instance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: homeserver

  source:
    repoURL: https://apache.github.io/couchdb-helm
    chart: couchdb
    targetRevision: 4.6.3
    helm:
      releaseName: couchdb
      values: |
        createAdminSecret: false


        couchdbConfig:
          couchdb:
            uuid: 7f4c1f6e-8c1b-4a6a-9d13-0f2b5d8e8b6f

        persistentVolume:
          enabled: true
          storageClass: longhorn
          size: 20Gi
          accessModes: 
            - ReadWriteOnce

        persistentVolumeClaimRetentionPolicy:
          enabled: true
          whenScaled: Retain
          whenDeleted: Retain

        service:
          enabled: true
          type: ClusterIP
          sessionAffinity: ClientIP

  destination:
    server: https://kubernetes.default.svc
    namespace: couchdb

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
