apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: couchdb-secret
  namespace: couchdb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: couchdb-couchdb
    creationPolicy: Owner
  data:
    - secretKey: adminUsername
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: COUCHDB_USER
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: adminPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: COUCHDB_PASSWORD
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: erlangCookie
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: COUCHDB_SECRET
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: cookieAuthSecret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: COUCHDB_SECRET
        metadataPolicy: None
        nullBytePolicy: Ignore
