apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homeserver
  namespace: argocd
spec:
  description: Homeserver project managed by Argo CD

  sourceRepos:
    - https://github.com/development-martin-rein/homeserver.git
    - quay.io/jetstack/charts
    - https://charts.longhorn.io
    - https://cloudnative-pg.github.io/charts
    - https://valkey.io/valkey-helm/
    - https://charts.external-secrets.io
    - https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    - https://metallb.github.io/metallb
    - https://apache.github.io/couchdb-helm

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
