apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-lan-ca
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: home-lan-ca
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: HOME_LAN_CA_CRT
    - secretKey: tls.key
      remoteRef:
        key: HOME_LAN_CA_KEY
