apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: 0.14.5
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: {}
