apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: obsidian-livesync-production
data:
  obsidian.ini: |
    [chttpd]
    enable_cors = true
    require_valid_user = true

    [httpd]
    enable_cors = true

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost,https://obsidian-sync.home.lan
    credentials = true
    methods = GET, PUT, POST, HEAD, DELETE
    headers = accept, authorization, content-type, origin, referer

    [couchdb]
    single_node = true
