apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-secret
  namespace: technitium-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: technitium-secret
    creationPolicy: Owner
  data:
    - secretKey: adminUser
      remoteRef:
        key: TECHNITIUM_ADMIN_USER
    - secretKey: adminPassword
      remoteRef:
        key: TECHNITIUM_ADMIN_PASSWORD
