apiVersion: v1
kind: Service
metadata:
  name: technitium
  namespace: technitium-dns
  annotations:
    metallb.io/loadBalancerIPs: 192.168.178.250
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: technitium
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
