apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: gitlab-production
spec:
  interval: 10m
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: gitlab-minio
        namespace: gitlab-production
      interval: 1h
  values:
    fullnameOverride: gitlab-minio
    mode: standalone
    existingSecret: gitlab-minio-root-credentials
    persistence:
      enabled: true
      storageClass: longhorn
      size: 50Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 1000m
    service:
      type: ClusterIP
      port: 9000
    consoleService:
      type: ClusterIP
      port: 9001
    buckets:
    - name: gitlab-artifacts
      policy: none
      purge: false
    - name: gitlab-lfs
      policy: none
      purge: false
    - name: gitlab-uploads
      policy: none
      purge: false
    - name: gitlab-packages
      policy: none
      purge: false
    - name: gitlab-mr-diffs
      policy: none
      purge: false
    - name: gitlab-terraform-state
      policy: none
      purge: false
    - name: gitlab-ci-secure-files
      policy: none
      purge: false
    - name: gitlab-dependency-proxy
      policy: none
      purge: false
    - name: gitlab-agent-plan-content
      policy: none
      purge: false
    - name: gitlab-backups
      policy: none
      purge: false
    - name: gitlab-tmp
      policy: none
      purge: false
    - name: gitlab-registry
      policy: none
      purge: false
