apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secret
  namespace: couchdb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: couchdb-secret
    creationPolicy: Owner
  data:
    - secretKey: COUCHDB_USER
      remoteRef:
        key: COUCHDB_USER
    - secretKey: COUCHDB_PASSWORD
      remoteRef:
        key: COUCHDB_PASSWORD
    - secretKey: COUCHDB_SECRET
      remoteRef:
        key: COUCHDB_SECRET
