apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: envoy-gateway-system
  releaseName: eg

  chart:
    spec:
      chart: gateway-helm
      version: v1.6.0
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
      reconcileStrategy: ChartVersion

  install:
    createNamespace: true

  values:
    envoyProxy:
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.178.40
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.178.40"

