apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 10m
  releaseName: envoy-gateway
  targetNamespace: envoy-gateway-system

  install:
    createNamespace: true

  upgrade:
    remediation:
      retry: 3

  chart:
    spec:
      chart: gateway-helm
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
      interval: 30m

  values:
    envoyGateway:
      proxy:
        service:
          type: LoadBalancer
