apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  # Wichtig: Registry-URL OHNE Chart-Namen
  url: oci://registry-1.docker.io/envoyproxy
  secretRef:
    name: dockerhub-secret 
