apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  type: oci
  url: oci://docker.io/envoyproxy/gateway-helm
  interval: 10m
  timeout: 1m
