apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: homeserver
  source:
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    chart: gateway-helm
    targetRevision: v1.8.0
    helm:
      releaseName: eg
      values: |
        deployment:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
