apiVersion: v1
kind: Secret
metadata:
    name: sops-test-secret
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:yET44xfonj0=,iv:BQAM/VgYmZxKyynRiLDJqkZ/EpiE7ugG75n+dflqNtg=,tag:ggiA4BB2WUqsYcZSOi1dkw==,type:str]
    password: ENC[AES256_GCM,data:ue+UM5BgZn6I2Hg0,iv:XKNr+NYwZIL0hYGouRqt79LsqtMvl5Imp3cl3Immot0=,tag:hsUfyEjD23yozwVcxLrRJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT3dsTW4zRzJwMnlaQUF5
            ei9hcGQ1TUlBL2Yrd3BzS0c3UTF5UTdiNzJJCkhWUnNGbVIyazF3T1dZY1RMblVt
            NFZ4THBmRGlKVmgzM3E4aU9JZkEwSGMKLS0tIHRoTTQ1eGpMV1pLWHdMOWxNZVA3
            aEE0clJ5Q0YwRXBpRmZVMHk1NmJEc2MKP5/5A39eFOa7U0CgjOI35+DfeaQEJ2uo
            9ZmdqWDYPzgq0meqy6WqiFDImFm49DQFJ5VLAuGRhOei2/l8S2VMoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3fu50cfre56f0kwutyzk5f62m6wgcc5m0r08jwhz4exyqgev5fq95ely6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T17:21:34Z"
    mac: ENC[AES256_GCM,data:NNJuC5lCZmM6dcYED0S5J7wsrYKeNxV4dVdxpZsmsD0zE8NH8fKMr/UXghnnjUjhqz+66cicq2pk3hYXqQDQpbWCkV6CBP9sJWZGEvI6i7kr1ouCTeCCYIyXxF5onb9V8C9FXAquOfA4lsjjzecMwQvNcwC5KjIbUCyylgx8sII=,iv:JfueZNFIOkx0ZjCwB7kbX0UisaFD8PH6GDZU3uin5gY=,tag:f9byBKP+DvQt+AOKgxcg8w==,type:str]
    version: 3.13.1
