apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.7.2           # Version bei Bedarf anpassen
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: false
  values:
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 2
